export const RouteStrings = {
  login: "/auth",
  signup: "signup",
  forgotpassword: "forgotpassword",
  dashboard: "/",
  subAdminSignUp: "subAdminSignUp",
  companydetails: "companydetails",
  leaves: "leaves",
  employeeApplyLeave: "employeeApplyLeave",
  leavestable: "leavestable",
  settings: "settings",
  createuser: "createuser",
  createrole: "createrole",
  payslips: "payslips",
  fields: "fields",
  404: "*",
};
